### ISSUE TITLE
Failed to install extension scheduler (v0.1.1). 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by editwentyone** [bitkarrot/scheduler#18]
unfortunately I get this error when I hit install, tried also with 0.1.0 same error.

no further informations available, can you help out and point into right direction?

lnbits 0.12.4 running on citadel node

**Comment by bitkarrot** [comment]
I'm not famiiar with running the citadel node but if you are running the LNBits inside of a docker container, this may not work.  It is best run on a standalone barebones setup on ubuntu. 

The user that runs LNBits server MUST have crontab -e permissions in order to read/write to crontab file. So you will need to enable that. (See the README file.)

**Comment by editwentyone** [comment]
done, moved to raspibolt :D just because of this.
